### ISSUE TITLE
商品首页打不开了，其他功能正常

### ISSUE THREAD

**Issue by Ais-Danny** [weiraneve/seckillcloud#12]
![image](https://github.com/weiraneve/seckillcloud/assets/91066083/5441dde0-3979-4d42-af4a-d7765c472ddd)
可以正常访问其他页面

**Comment by weiraneve** [comment]
是在`seckill-front`的首页打开的时候，`seckill_cloud`后端报错吗

**Comment by Ais-Danny** [comment]
是的

**Comment by Ais-Danny** [comment]
今天试了图片上传没问题了，就是首页打不开了

**Comment by Ais-Danny** [comment]
今天试了图片上传没问题了，就是首页打不开了

**Comment by weiraneve** [comment]
我这边首页打开，是正常的，终端打印的日志也是正常的。未能复现。

**Comment by Ais-Danny** [comment]
应该是redis或者mq缓存有问题

**Comment by Ais-Danny** [comment]
我把redis和mq清了就好了

**Comment by weiraneve** [comment]
well done👍

**Comment by Ais-Danny** [comment]
大佬，那个渲染提示问题能不能修复一下

**Comment by weiraneve** [comment]
那个问题我试着修复过😂，有点难度

**Comment by Ais-Danny** [comment]
注册成功和注册手机号重复都没有提示，但是看请求响应里面有

**Comment by Ais-Danny** [comment]
vue我不太熟

**Comment by Ais-Danny** [comment]
看不懂

**Comment by weiraneve** [comment]
那个就是dom元素不知道为啥被覆盖住了，很奇怪，我再check下吧

**Comment by Ais-Danny** [comment]
但是我看html里面也没有这个元素出现呀

**Comment by weiraneve** [comment]
`ant-message` 这个元素，当你发送表单的时候，错误会有这个元素，就三秒钟

**Comment by Ais-Danny** [comment]
我就是发表单没看见😂

**Comment by Ais-Danny** [comment]
这个元素内容一直是空的

**Comment by Ais-Danny** [comment]
![Uploading image.png…]()
未见对请求响应的处理

**Comment by weiraneve** [comment]
我回滚到之前没使用vite的版本，解决了这个问题，其他功能应该没有被影响

**Comment by Ais-Danny** [comment]
感觉这个版本还好看些🤣

**Comment by weiraneve** [comment]
🤣
