### ISSUE TITLE
后台管理员模块撤销对普通管理员的授权

### ISSUE THREAD

**Issue by Ais-Danny** [weiraneve/seckillcloud#13]
1.撤销授权后商品的确无法修改其属性，但并未给出任何提示。
2.商品的启用开关仍可打开（虽然无法发送请求，但界面未给予禁止）
3.订单仍可以查询
4.库存也可以查询

**Comment by weiraneve** [comment]
看之后有时间给fix下🥹

**Comment by weiraneve** [comment]
已fix
