### ISSUE TITLE
管理员头像更改异常

### ISSUE THREAD

**Issue by Ais-Danny** [weiraneve/seckillcloud#14]
![image](https://github.com/weiraneve/seckillcloud/assets/91066083/6a07bd85-313d-42bc-892f-11a0c24653c3)
![Uploading image.png…]()

**Comment by Ais-Danny** [comment]
![image](https://github.com/weiraneve/seckillcloud/assets/91066083/f98de8e4-775b-4952-93e7-19469c0ca248)

**Comment by weiraneve** [comment]
<img width="671" alt="bug_inexistence" src="https://github.com/weiraneve/seckillcloud/assets/60456779/1da2cae6-3e75-4183-8a59-282c37b7dbe0">

我这边测试为正常，未能复现问题，是不是你这边本地环境跟qiniu云OSS相关的功能都有异常。
