### ISSUE TITLE
docker-compose文件问题

### ISSUE THREAD

**Issue by Ais-Danny** [weiraneve/seckillcloud#9]
nacos版本不可用（x86架构不可用）
mysql 端口号映射错误

**Comment by weiraneve** [comment]
这是有点问题，以前我在尝试cover docker-compose的时候，因为我自己电脑是arm架构，x86的在我电脑上跑不了，然后我就没继续深究跑通docker-compose的事情了🥹

**Comment by Ais-Danny** [comment]
我的弱鸡服务器跑不动🥹，只能拆分跑。搞不懂为啥跑个java程序服务器pbs巨高，直接给我卡死到都关不了机

**Comment by weiraneve** [comment]
那是有点恼火，java程序就是这样，吃内存大户

**Comment by weiraneve** [comment]
感谢解决，现在已适配x86 arm64机器
